@host=http://localhost:5087

POST {{host}}/Authentication/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "JohnDoeTheOneAndOnly@gmail.com",
    "password": "MY_VERY_STRONG_PASSWORD",
    "isAgent": false,
    "description": "John Doe is a test user"
}