# @host=https://simyou.azurewebsites.net
@host=http://localhost:5087

POST {{host}}/Authentication/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "NPC",
    "lastName": "Man",
    "isAgent": true,
    "description": "I am a former president and overall good guy!."
}
