@host=http://localhost:5087
@userId=cb8e1fcd-00f0-498d-b9a3-da00e3e05b61

POST {{host}}/Users/{{userId}}/responses HTTP/1.1
Content-Type: application/json

[
    "Blue",
    "Dog",
    "Pizza",
    "Inception",
    "1984 by George Orwell",
    "Bohemian Rhapsody by Queen",
    "Chess",
    "Basketball",
    "Reading",
    "The beach"
]