name: deploy-to-prod

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa api.simugameservice.lekina.me >> ~/.ssh/known_hosts

      - name: Deploy to Production
        run: |
          chmod +x deploy.sh
          ./deploy.sh





